name: development-checks

on:
  push:
    branches:
      - "main" 

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r main/requirements.txt
          pip install pylint
      - name: Run tests
        run: |
          cd main
          export PYTHONPATH="$PWD:$PYTHONPATH"
          cd test
          bash test_pylint.sh
          bash test_schema.sh
